SELECT
  C.CONTEST_ID,
  C.HACKER_ID,
  C.NAME,
  SUM(TOTAL_SUBMISSIONS),
  SUM(TOTAL_ACCEPTED_SUBMISSIONS),
  SUM(TOTAL_VIEWS),
  SUM(TOTAL_UNIQUE_VIEWS)
FROM CONTESTS C
  JOIN COLLEGES CG
  ON C.CONTEST_ID = CG.CONTEST_ID
  JOIN CHALLENGES CH
  ON CG.COLLEGE_ID = CH.COLLEGE_ID
  LEFT JOIN (
    SELECT
      CHALLENGE_ID,
      SUM(TOTAL_VIEWS) AS TOTAL_VIEWS,
      SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
    FROM VIEW_STATS
    GROUP BY
      CHALLENGE_ID
  ) VS
  ON CH.CHALLENGE_ID = VS.CHALLENGE_ID
  LEFT JOIN (
    SELECT
      CHALLENGE_ID,
      SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS,
      SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS
    FROM SUBMISSION_STATS
    GROUP BY
      CHALLENGE_ID
  ) SS
  ON CH.CHALLENGE_ID = SS.CHALLENGE_ID
GROUP BY C.CONTEST_ID, C.HACKER_ID, C.NAME
HAVING
  SUM(TOTAL_SUBMISSIONS) != 0 OR
  SUM(TOTAL_ACCEPTED_SUBMISSIONS) != 0 OR
  SUM(TOTAL_VIEWS) != 0 OR
  SUM(TOTAL_UNIQUE_VIEWS) != 0
ORDER BY CONTEST_ID;