SELECT
  H.HACKER_ID,
  H.NAME,
  COUNT(C.CHALLENGE_ID) AS CH_COUNTER
FROM HACKERS H
  JOIN CHALLENGES C
  ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING CH_COUNTER IN (
    SELECT TEMP.COUNTER
    FROM (
      SELECT
        HACKER_ID,
        COUNT(CHALLENGE_ID) AS COUNTER
      FROM CHALLENGES
      GROUP BY HACKER_ID
      ORDER BY COUNTER DESC
    ) TEMP
    GROUP BY TEMP.COUNTER
    HAVING COUNT(TEMP.COUNTER) = 1
  ) ORCH_COUNTER IN (
    SELECT MAX(TEMP.COUNTER)
    FROM (
      SELECT
        HACKER_ID,
        COUNT(CHALLENGE_ID) AS COUNTER
      FROM CHALLENGES
      GROUP BY HACKER_ID
      ORDER BY COUNTER DESC
    ) TEMP
  )
ORDER BY CH_COUNTER DESC, H.HACKER_ID ASC;