SELECT
  C.COMPANY_CODE,
  C.FOUNDER,
  COUNT(DISTINCT LM.LEAD_MANAGER_CODE),
  COUNT(DISTINCT SM.SENIOR_MANAGER_CODE),
  COUNT(DISTINCT M.MANAGER_CODE),
  COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY C
  LEFT JOIN LEAD_MANAGER LM
  ON C.COMPANY_CODE = LM.COMPANY_CODE
  LEFT JOIN SENIOR_MANAGER SM
  ON LM.LEAD_MANAGER_CODE = SM.LEAD_MANAGER_CODE
  LEFT JOIN MANAGER M
  ON SM.SENIOR_MANAGER_CODE = M.SENIOR_MANAGER_CODE
  LEFT JOIN EMPLOYEE E
  ON M.MANAGER_CODE = E.MANAGER_CODE
GROUP BY C.COMPANY_CODE, C.FOUNDER
ORDER BY C.COMPANY_CODE ASC