SELECT S.NAME
FROM STUDENTS AS S
  JOIN FRIENDS AS F
  ON S.ID = F.ID
  JOIN PACKAGES AS P
  ON F.ID = P.ID
  JOIN PACKAGES AS P2
  ON F.FRIEND_ID = P2.ID
WHERE P.SALARY < P2.SALARY
ORDER BY P2.SALARY;