SELECT CONCAT(NAME,
  CASE 
    WHEN OCCUPATION = "Actor" THEN "(A)"
    WHEN OCCUPATION = "Doctor" THEN "(D)"
    WHEN OCCUPATION = "Professor" THEN "(P)"
    ELSE "(S)"
  END
) FROM OCCUPATIONS ORDER BY NAME;

SELECT CONCAT(
  "There are a total of ",
  COUNT(OCCUPATION),
  " ",
  LOWER(OCCUPATION),
  "s."
) FROM OCCUPATIONS GROUP BY OCCUPATION ORDER BY COUNT(OCCUPATION) ASC;